// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DAL.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace DAL.Entities.Configurations
{
    public partial class BeerRatingConfiguration : IEntityTypeConfiguration<BeerRating>
    {
        public void Configure(EntityTypeBuilder<BeerRating> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__BeerRati__3214EC07C2FEEAD7");

            entity.HasOne(d => d.Beer).WithMany(p => p.BeerRatings).HasConstraintName("FK__BeerRatin__BeerI__398D8EEE");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<BeerRating> entity);
    }
}
