// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DAL.Entities.Configurations;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
#nullable enable

namespace DAL.Entities;

public partial class BeerCollectionContext : DbContext
{
    public BeerCollectionContext(DbContextOptions<BeerCollectionContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Beer> Beers { get; set; }

    public virtual DbSet<BeerRating> BeerRatings { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new Configurations.BeerConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.BeerRatingConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
