// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DAL.Entities;

[Table("BeerRating")]
public partial class BeerRating
{
    [Key]
    public long Id { get; set; }

    [Column(TypeName = "decimal(2, 1)")]
    public decimal Rate { get; set; }

    public long? BeerId { get; set; }

    [ForeignKey("BeerId")]
    [InverseProperty("BeerRatings")]
    public virtual Beer? Beer { get; set; }
}